# Generated by Django 2.2.13 on 2020-06-26 21:27

import common.enums
import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0004_refresh_action_view'),
        ('multi_tenant', '0014_subscriberintegrationproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('external_tool', common.fields.TurnoutEnumField(enum=common.enums.ExternalToolType, null=True)),
                ('external_id', models.TextField(null=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.Action')),
                ('subscriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_tenant.Client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
