# Generated by Django 2.2.16 on 2020-09-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_moverlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moverlead',
            name='new_state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moverlead',
            name='old_state',
            field=models.TextField(null=True),
        ),
    ]
