# Generated by Django 2.2.16 on 2020-09-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0006_region_hidden'),
        ('integration', '0004_mymove_state_drop_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='moverlead',
            name='new_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moverlead_new', to='official.Region'),
        ),
        migrations.AddField(
            model_name='moverlead',
            name='old_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moverlead_old', to='official.Region'),
        ),
    ]
