# Generated by Django 2.2.16 on 2020-09-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0010_index_last_voter_lookup'),
        ('storage', '0008_storageitem_preview_of'),
        ('integration', '0005_mover_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='moverlead',
            name='blank_register_forms_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Action'),
        ),
        migrations.AddField(
            model_name='moverlead',
            name='blank_register_forms_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.StorageItem'),
        ),
    ]
