# Generated by Django 2.2.16 on 2020-09-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_mover_blank_forms_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moverlead',
            name='source_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='moverlead',
            table=None,
        ),
    ]
