# Generated by Django 2.2.12 on 2020-05-28 00:55

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_active_client_nullable'),
    ]

    operations = [
        # Add the field and set everyone's record to "US/Pacific"
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='US/Pacific', null=True),
        ),
        # Now make the default for new users 'US/Eastern' and restrict to US timezones and UTC
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices=[('US/Alaska', 'US/Alaska'), ('US/Arizona', 'US/Arizona'), ('US/Central', 'US/Central'), ('US/Eastern', 'US/Eastern'), ('US/Hawaii', 'US/Hawaii'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('UTC', 'UTC')], default='US/Eastern', null=True),
        ),
    ]
