# Generated by Django 2.2.12 on 2020-06-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_election_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='Election Information Admin'),
        ),
    ]
