# Generated by Django 2.2.14 on 2020-07-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_election_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscriber_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='Subscriber Admin'),
        ),
    ]
