# Generated by Django 2.2.15 on 2020-08-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_smalluuid_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_esign_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='Esign Admin'),
        ),
    ]
