# Generated by Django 2.2.15 on 2020-08-27 13:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.TextField(null=True)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('kwargs', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('due_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
