# Generated by Django 2.2.16 on 2020-09-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='delayedtask',
            index=models.Index(fields=['due_at', 'started_at'], name='common_dela_due_at_ce758b_idx'),
        ),
    ]
