FROM python:3.7-buster

ENV APP_DIR=/app
WORKDIR $APP_DIR

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs pdftk-java imagemagick ghostscript wait-for-it gdal-bin postgis && \
    apt-get clean

COPY docker/imagemagick-dev-policy.xml /etc/ImageMagick-6/policy.xml

COPY app/package.json app/package-lock.json $APP_DIR/
RUN npm install

COPY app/requirements.txt $APP_DIR/
RUN pip install -r requirements.txt
