# Generated by Django 2.2.12 on 2020-04-17 02:36

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storageitem_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='app',
            field=common.fields.TurnoutEnumField(enum=common.enums.FileType),
        ),
    ]
