# Generated by Django 2.2.12 on 2020-05-07 02:10

import common.enums
import common.fields
from django.db import migrations, models
import django_smalluuid.models
import storage.backends


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_enumchartotextfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureUploadItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(storage=storage.backends.HighValueStorage(), upload_to='')),
                ('upload_type', common.fields.TurnoutEnumField(enum=common.enums.SecureUploadType)),
                ('content_type', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
