# Generated by Django 2.2.12 on 2020-05-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0012_rename_partner_subscriber'),
        ('storage', '0004_secureuploaditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='partner',
            field=models.ForeignKey(db_column='partner_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='multi_tenant.Client'),
        ),
        migrations.RenameField('StorageItem', 'partner', 'subscriber'),
    ]
