# Generated by Django 2.2.15 on 2020-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_smalluuid_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureuploaditem',
            name='purged',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='purged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
