# Generated by Django 2.2.15 on 2020-08-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20200805_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='preview_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.StorageItem'),
        ),
    ]
