# Generated by Django 2.2.16 on 2020-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_place', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pollingplacelookup',
            index=models.Index(fields=['created_at'], name='polling_pla_created_e46ea6_idx'),
        ),
    ]
