# Generated by Django 2.2.14 on 2020-07-15 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
import phonenumber_field.modelfields
import tsvector_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0001_initial'),
        ('multi_tenant', '0001_initial'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('embed_url', models.TextField(blank=True, null=True)),
                ('utm_campaign', models.TextField(blank=True, null=True)),
                ('utm_source', models.TextField(blank=True, null=True)),
                ('utm_medium', models.TextField(blank=True, null=True)),
                ('utm_term', models.TextField(blank=True, null=True)),
                ('utm_content', models.TextField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('sms_opt_in_subscriber', models.BooleanField(db_column='sms_opt_in_partner', default=False, null=True)),
                ('search', tsvector_field.SearchVectorField(columns=[tsvector_field.WeightedColumn('email', 'A'), tsvector_field.WeightedColumn('last_name', 'A'), tsvector_field.WeightedColumn('first_name', 'A')], language='english')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Zip codes are 5 digits')])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sms_opt_in', models.BooleanField(blank=True, default=None, null=True)),
                ('action', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Action')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.State')),
                ('subscriber', models.ForeignKey(db_column='partner_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='multi_tenant.Client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
