# Generated by Django 2.2.14 on 2020-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderrequest',
            name='age',
        ),
        migrations.AddField(
            model_name='reminderrequest',
            name='email_referrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminderrequest',
            name='mobile_referrer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
