# Generated by Django 2.2.12 on 2020-04-08 21:33

import common.enums
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
import enumfields.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BallotRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('utm_campaign', models.TextField(blank=True, null=True)),
                ('utm_source', models.TextField(blank=True, null=True)),
                ('utm_medium', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(null=True)),
                ('middle_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('suffix', models.TextField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('address1', models.TextField(null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(null=True)),
                ('zipcode', models.TextField(null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Zip codes are 5 digits')])),
                ('mailing_address1', models.TextField(blank=True, null=True)),
                ('mailing_address2', models.TextField(blank=True, null=True)),
                ('mailing_city', models.TextField(blank=True, null=True)),
                ('mailing_zipcode', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Zip codes are 5 digits')])),
                ('us_citizen', models.BooleanField(default=False, null=True)),
                ('sms_opt_in', models.BooleanField(default=False, null=True)),
                ('status', enumfields.fields.EnumField(default='Pending', enum=common.enums.TurnoutBallotRequestStatus, max_length=10, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
