# Generated by Django 2.2.12 on 2020-04-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('multi_tenant', '0001_initial'),
        ('action', '0001_initial'),
        ('election', '0001_initial'),
        ('absentee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotrequest',
            name='action',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Action'),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='mailing_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absentee_mailing', to='election.State'),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='multi_tenant.Client'),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='result_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.StorageItem'),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absentee_primary', to='election.State'),
        ),
    ]
