# Generated by Django 2.2.12 on 2020-04-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0001_initial'),
        ('absentee', '0002_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotrequest',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='official.Region'),
        ),
    ]
