# Generated by Django 2.2.12 on 2020-04-17 02:36

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absentee', '0003_ballotrequest_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotrequest',
            name='status',
            field=common.fields.TurnoutEnumField(default='Pending', enum=common.enums.TurnoutActionStatus, null=True),
        ),
    ]
