# Generated by Django 2.2.12 on 2020-05-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_secureuploaditem'),
        ('absentee', '0005_ballotrequest_sms_opt_in_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotrequest',
            name='signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.SecureUploadItem'),
        ),
    ]
