# Generated by Django 2.2.12 on 2020-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absentee', '0009_utm_term_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotrequest',
            name='submit_date',
            field=models.DateField(null=True),
        ),
    ]
