# Generated by Django 2.2.12 on 2020-05-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0001_initial'),
        ('absentee', '0009_utm_term_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbsenteeLeoEmailOverride',
            new_name='LeoContactOverride',
        ),
    ]
