# Generated by Django 2.2.12 on 2020-05-22 18:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('absentee', '0010_auto_20200522_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='leocontactoverride',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='leocontactoverride',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='leocontactoverride',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
