# Generated by Django 2.2.12 on 2020-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absentee", "0011_auto_20200522_1807"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotrequest",
            name="submit_date",
            field=models.DateField(null=True),
        ),
    ]
