# Generated by Django 2.2.13 on 2020-06-04 16:19

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absentee', '0013_rename_partner_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotrequest',
            name='esign_method',
            field=common.fields.TurnoutEnumField(enum=common.enums.SubmissionType, null=True),
        ),
    ]
