# Generated by Django 2.2.14 on 2020-07-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0005_regiongeomma_regiongeomwi'),
        ('absentee', '0016_tracking_embed_url_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionOVBMLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='official.Region')),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['region__state__code', 'region__name'],
            },
        ),
    ]
