# Generated by Django 2.2.14 on 2020-07-14 21:11

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absentee', '0017_regionovbmlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='leocontactoverride',
            name='submission_method',
            field=common.fields.TurnoutEnumField(enum=common.enums.SubmissionType, null=True),
        ),
    ]
