# Generated by Django 2.2.14 on 2020-07-14 21:11

from django.db import migrations, models

import common.enums
import common.fields

from . import DASHBOARD_VIEWS_CREATE_SQL, DASHBOARD_VIEWS_DROP_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("absentee", "0019_actionnetwork_tracking"),
        ("official", "0006_region_hidden"),
        ("election", "0008_auto_20200629_2252"),
        ("event_tracking", "0004_add_event_type_created_at_index"),
    ]

    operations = [
        migrations.RunSQL(
            DASHBOARD_VIEWS_CREATE_SQL, reverse_sql=DASHBOARD_VIEWS_DROP_SQL
        ),
        migrations.CreateModel(
            name="RegionEsignMethod",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="esign",
                        serialize=False,
                        to="official.Region",
                    ),
                ),
                ("has_override", models.BooleanField()),
                (
                    "submission_method",
                    common.fields.TurnoutEnumField(enum=common.enums.SubmissionType),
                ),
            ],
            options={"managed": False, "ordering": ["state_id", "region__name"]},
        ),
        migrations.CreateModel(
            name="StateDashboardData",
            fields=[
                (
                    "state",
                    models.OneToOneField(
                        on_delete=models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="absentee_dashboard_data",
                        serialize=False,
                        to="election.State",
                    ),
                ),
                ("has_statewide_link", models.BooleanField()),
                ("num_region_links", models.IntegerField()),
                ("fax_allowed", models.BooleanField()),
                ("email_allowed", models.BooleanField()),
                ("num_regions", models.IntegerField()),
                ("num_regions_email", models.IntegerField()),
                ("num_regions_fax", models.IntegerField()),
                ("num_regions_self_print", models.IntegerField()),
                ("num_regions_with_override", models.IntegerField()),
            ],
            options={"managed": False, "ordering": ["state_id"]},
        ),
        migrations.CreateModel(
            name="EsignSubmitStats",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="esign_stats",
                        serialize=False,
                        to="official.Region",
                    ),
                ),
                ("emails_sent_7d", models.IntegerField()),
                ("faxes_sent_7d", models.IntegerField()),
                ("emails_sent_1d", models.IntegerField()),
                ("faxes_sent_1d", models.IntegerField()),
            ],
            options={"managed": False, "ordering": ["state_id", "region__name"]},
        ),
        migrations.AddField(
            model_name="leocontactoverride",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
