# Generated by Django 2.2.15 on 2020-08-22 17:08

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absentee', '0021_smalluuid_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotrequest',
            name='referring_tool',
            field=common.fields.TurnoutEnumField(blank=True, enum=common.enums.ToolName, null=True),
        ),
    ]
