# Generated by Django 2.2.15 on 2020-08-24 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_storageitem_preview_of'),
        ('election', '0013_state_allow_print_and_forward'),
        ('absentee', '0022_ballotrequest_referring_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotrequest',
            name='deliverable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='mailing_deliverable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='request_mailing_address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='request_mailing_address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='request_mailing_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='request_mailing_deliverable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='request_mailing_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absentee_request_mailing', to='election.State'),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='request_mailing_zipcode',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Zip codes are 5 digits')]),
        ),
        migrations.AddField(
            model_name='ballotrequest',
            name='result_item_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absentee_mail', to='storage.StorageItem'),
        ),
    ]
