# Generated by Django 2.2.16 on 2020-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absentee', '0025_index_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ballotrequest',
            index=models.Index(fields=['created_at'], name='absentee_ba_created_b1e383_idx'),
        ),
    ]
