# Generated by Django 2.2.10 on 2020-02-12 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multifactor.models
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UUIDTOTPDevice',
            fields=[
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True)),
                ('throttling_failure_count', models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.TextField(default=multifactor.models.default_key, help_text='A hex-encoded secret key of up to 40 bytes.', validators=[multifactor.models.key_validator])),
                ('digits', models.PositiveSmallIntegerField(default=6, help_text='The number of digits to expect in a token.')),
                ('start_time', models.BigIntegerField(default=0, help_text='The Unix time at which to begin counting steps.')),
                ('last_time', models.BigIntegerField(default=-1, help_text='The t value of the latest verified token. The next token must be at a higher time step.')),
                ('step', models.PositiveSmallIntegerField(default=30, help_text='The time step in seconds.')),
            ],
            options={
                'verbose_name': 'TOTP device',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
