# Generated by Django 2.2.10 on 2020-02-12 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('multifactor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuidtotpdevice',
            name='user',
            field=models.ForeignKey(default='', help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
