# Generated by Django 2.2.12 on 2020-05-19 18:19

from django.db import migrations, models
import django.db.models.deletion

from action.migrations import ACTIONDETAIL_VIEW_CREATION_SQL, ACTIONDETAIL_VIEW_REVERSE_SQL

class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('event_tracking', '0003_event_type_db_index'),
    ]

    operations = [
        migrations.RunSQL(ACTIONDETAIL_VIEW_CREATION_SQL, reverse_sql=ACTIONDETAIL_VIEW_REVERSE_SQL),
        migrations.CreateModel(
            name='ActionDetails',
            fields=[
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='action.Action')),
                ('finished', models.BooleanField()),
                ('self_print', models.BooleanField(db_column='self_print', null=True)),
                ('finished_external_service', models.BooleanField(db_column='finish_external', null=True)),
                ('leo_message_sent', models.BooleanField(db_column='finish_leo', null=True)),
                ('total_downloads', models.IntegerField(db_column='download_count', null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
