# Generated by Django 2.2.15 on 2020-08-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_refresh_action_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='last_voter_lookup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
