# Generated by Django 2.2.15 on 2020-08-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0008_action_last_voter_lookup'),
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voter.Voter'),
        ),
    ]
