# Generated by Django 2.2.16 on 2020-09-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0009_action_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='last_voter_lookup',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
