# Generated by Django 2.2.16 on 2020-11-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0011_refresh_views'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['created_at'], name='action_acti_created_608cc0_idx'),
        ),
    ]
