# Generated by Django 2.2.17 on 2020-12-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0012_action_index_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='visible_to_subscriber',
            field=models.BooleanField(db_index=True, default=True, null=True),
        ),
    ]
