# Generated by Django 2.2.15 on 2020-08-04 15:46

import common.enums
import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsbot', '0002_smalluuid_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='status',
            field=common.fields.TurnoutEnumField(enum=common.enums.SMSDeliveryStatus, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='status_time',
            field=models.DateTimeField(null=True),
        ),
    ]
