# Generated by Django 2.2.15 on 2020-08-26 21:04

import uuid
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('smsbot', '0004_dedup_phone'),
        ('voter', '0002_clear_voter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='number',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False),
        ),
    ]
