# Generated by Django 2.2.15 on 2020-08-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsbot', '0005_change_number_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsbot.Number'),
        ),
    ]
