# Generated by Django 2.2.15 on 2020-08-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsbot', '0006_msg_foreign_key_to_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='twilio_sid',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
