# Generated by Django 2.2.16 on 2020-10-29 19:58

import common.enums
import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsbot', '0010_blast_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='blast',
            name='blast_type',
            field=common.fields.TurnoutEnumField(enum=common.enums.BlastType, null=True),
        ),
        migrations.AlterField(
            model_name='blast',
            name='campaign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blast',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
