# Generated by Django 2.2.12 on 2020-05-22 16:35

import common.enums
import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', common.fields.TurnoutEnumField(enum=common.enums.ReportStatus, null=True, default=common.enums.ReportStatus.PENDING)),
                ('type', common.fields.TurnoutEnumField(enum=common.enums.ReportType, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
