# Generated by Django 2.2.12 on 2020-05-24 22:56

import django.db.models.deletion
from django.db import migrations, models

from reporting.migrations import VIEW_CREATE_SQL, VIEW_DROP_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_rename_partner_subscriber"),
        ("verifier", "0018_tracking_embed_url_session_id"),
        ("absentee", "0016_tracking_embed_url_session_id"),
        ("register", "0016_tracking_embed_url_session_id"),
    ]

    operations = [
        migrations.RunSQL(VIEW_CREATE_SQL, reverse_sql=VIEW_DROP_SQL),
    ]
