# Generated by Django 2.2.12 on 2020-05-24 22:56

import django.db.models.deletion
from django.db import migrations, models

from reporting.migrations import VIEW_CREATE_SQL, VIEW_DROP_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0005_smalluuid_to_uuid"),
    ]

    operations = [
        migrations.RunSQL(VIEW_CREATE_SQL),
    ]
