# Generated by Django 2.2.9 on 2019-12-20 01:03

from django.db import migrations

def create_initial_client(apps, schema_editor):
    Client = apps.get_model('multi_tenant', 'Client')
    Client.objects.get_or_create(
        defaults={
            'name': 'Default',
            'url': 'https://localhost:9001/'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0002_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(create_initial_client, lambda x,y: None)
    ]
