# Generated by Django 2.2.9 on 2020-02-10 20:17

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invite'),
        ('multi_tenant', '0003_initial_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteAssociation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_tenant.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Invite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
