# Generated by Django 2.2.12 on 2020-04-10 18:36

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
from django.template.defaultfilters import slugify


def create_initial_slugs(apps, schema_editor):
    Client = apps.get_model('multi_tenant', 'Client')
    PartnerSlug = apps.get_model('multi_tenant', 'PartnerSlug')
    for client in Client.objects.all():
        PartnerSlug.objects.get_or_create(
            partner=client,
            slug=slugify(client.name)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0005_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSlug',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_tenant.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_initial_slugs, lambda x,y: None),
    ]
