# Generated by Django 2.2.12 on 2020-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0006_partnerslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerslug',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
