# Generated by Django 2.2.12 on 2020-04-29 17:57

from django.db import migrations, models


def set_default_terms_and_privacy(apps, schema_editor):
    Client = apps.get_model('multi_tenant', 'Client')
    for client in Client.objects.all():
        client.terms_of_service = "http://turnout.local/terms"
        client.privacy_policy = "http://turnout.local/privacy"
        client.save()



class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0007_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='privacy_policy',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sms_checkbox_default',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sms_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='terms_of_service',
            field=models.URLField(null=True),
        ),
        migrations.RunPython(set_default_terms_and_privacy, lambda x,y: None),
    ]
