# Generated by Django 2.2.12 on 2020-05-06 21:27

from django.db import migrations, models
import django.db.models.deletion

def set_default_slug(apps, schema_editor):
    Client = apps.get_model('multi_tenant', 'Client')
    for client in Client.objects.all():
        client.default_slug = client.partnerslug_set.first()
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0008_embed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_slug',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='multi_tenant.PartnerSlug'),
        ),
        migrations.RunPython(set_default_slug, lambda x,y: None),
    ]
