# Generated by Django 2.2.12 on 2020-05-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0009_default_partnerslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_checkbox',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sms_disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
