# Generated by Django 2.2.12 on 2020-05-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0010_additional_sms_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sync_tmc',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
