# Generated by Django 2.2.12 on 2020-05-24 22:50

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0011_client_sync_tmc'),
    ]

    operations = [
        # Tell future django migrations the model has been renamed
        migrations.RenameModel('PartnerSlug', 'SubscriberSlug'),
        # Tell future django migrations the table now has the old table name
        migrations.AlterModelTable(
            name='subscriberslug',
            table='multi_tenant_partnerslug',
        ),
        # Tell django to consider the field renamed
        migrations.RenameField('SubscriberSlug', 'partner', 'subscriber'),
        # Tell future django migrations that the db column is partner
        migrations.AlterField(
            model_name='subscriberslug',
            name='subscriber',
            field=models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.CASCADE, to='multi_tenant.Client'),
        ),
    ]
