# Generated by Django 2.2.13 on 2020-06-05 20:29

from django.db import migrations, models


def set_first_party(apps, schema_editor):
    Client = apps.get_model("multi_tenant", "Client")

    for client in Client.objects.filter(url__icontains="https://www.voteamerica.com"):
        client.is_first_party = True
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ("multi_tenant", "0012_rename_partner_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_first_party",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_first_party, lambda x, y: None),
    ]
