# Generated by Django 2.2.13 on 2020-06-26 21:27

import common.enums
import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0013_client_is_first_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberIntegrationProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('external_tool', common.fields.TurnoutEnumField(enum=common.enums.ExternalToolType, null=True)),
                ('name', models.TextField(null=True)),
                ('value', models.TextField(null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_tenant.Client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
