# Generated by Django 2.2.14 on 2020-07-19 22:55

import common.enums
import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0015_manage_settings_page_bluelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=common.fields.TurnoutEnumField(default='active', enum=common.enums.SubscriberStatus, null=True),
        ),
    ]
