# Generated by Django 2.2.15 on 2020-08-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0018_auto_20200804_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='info@voteamerica.com', max_length=254, null=True, verbose_name="Default 'From' Email Address"),
        ),
        migrations.AlterField(
            model_name='client',
            name='privacy_policy',
            field=models.URLField(blank=True, null=True, verbose_name='Privacy Policy URL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sms_checkbox',
            field=models.BooleanField(default=True, null=True, verbose_name='SMS Checkbox Enabled'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sms_checkbox_default',
            field=models.BooleanField(default=False, null=True, verbose_name='SMS Checkbox Checked By Default'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sms_disclaimer',
            field=models.TextField(blank=True, null=True, verbose_name='Custom SMS Disclaimer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sms_enabled',
            field=models.BooleanField(default=True, null=True, verbose_name='SMS Program Enabled'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sync_bluelink',
            field=models.BooleanField(default=False, null=True, verbose_name='Bluelink Sync Enabled'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sync_tmc',
            field=models.BooleanField(default=False, null=True, verbose_name='TMC Sync Enabled'),
        ),
        migrations.AlterField(
            model_name='client',
            name='terms_of_service',
            field=models.URLField(blank=True, null=True, verbose_name='Terms of Service URL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(verbose_name='Homepage URL'),
        ),
    ]
