# Generated by Django 2.2.16 on 2020-09-15 13:41

from django.db import migrations, models


def change_default_email(apps, schema_editor):
    Client = apps.get_model('multi_tenant', 'Client')
    for client in Client.objects.filter(email='info@voteamerica.com'):
        client.email = 'hello@voteamerica.com'
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0020_enable_api_on_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='hello@voteamerica.com', max_length=254, null=True, verbose_name="Default 'From' Email Address"),
        ),
        migrations.RunPython(change_default_email, lambda x,y: None)
    ]
