# Generated by Django 2.2.14 on 2020-07-30 15:52

import common.enums
import common.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('state', common.fields.TurnoutEnumField(enum=common.enums.ProxyStatus, null=True)),
                ('failure_count', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('state_up', models.BooleanField(null=True)),
                ('state_changed_at', models.DateTimeField(null=True)),
                ('last_tweet_at', models.DateTimeField(null=True)),
                ('uptime_day', models.FloatField(null=True)),
                ('uptime_week', models.FloatField(null=True)),
                ('uptime_month', models.FloatField(null=True)),
                ('uptime_quarter', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_up', models.BooleanField(null=True)),
                ('ignore', models.BooleanField(null=True)),
                ('load_time', models.FloatField(null=True)),
                ('error', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('proxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leouptime.Proxy')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leouptime.Site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteDowntime',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('down_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_down', to='leouptime.SiteCheck')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leouptime.Site')),
                ('up_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_up', to='leouptime.SiteCheck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='last_went_down_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_down', to='leouptime.SiteCheck'),
        ),
        migrations.AddField(
            model_name='site',
            name='last_went_up_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_up', to='leouptime.SiteCheck'),
        ),
    ]
