# Generated by Django 2.2.16 on 2020-09-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leouptime', '0002_proxy_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecheck',
            name='blocked',
            field=models.BooleanField(null=True),
        ),
    ]
