# Generated by Django 2.2.16 on 2020-09-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leouptime', '0004_site_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='last_went_blocked_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_blocked', to='leouptime.SiteCheck'),
        ),
        migrations.AddField(
            model_name='site',
            name='last_went_unblocked_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_unblocked', to='leouptime.SiteCheck'),
        ),
    ]
