# Generated by Django 2.2.14 on 2020-07-28 19:28

import apikey.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("multi_tenant", "0017_smalluuid_to_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "secret",
                    models.TextField(default=apikey.models.secret_token, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        db_column="partner_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="multi_tenant.Client",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
