# Generated by Django 2.2.15 on 2020-08-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
