# Generated by Django 2.2.12 on 2020-05-28 20:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fax',
            name='to',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
