# Generated by Django 2.2.12 on 2020-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fax', '0002_fax_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='fax',
            name='on_complete_task',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fax',
            name='on_complete_task_arg',
            field=models.TextField(null=True),
        ),
    ]
