# Generated by Django 2.2.9 on 2020-01-23 18:13

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django_smalluuid.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('registered', models.BooleanField(null=True)),
                ('too_many', models.BooleanField(null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('street_number', models.TextField(blank=True, null=True)),
                ('street_name', models.TextField(blank=True, null=True)),
                ('unparsed_full_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Zip codes are 5 digits')])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
