# Generated by Django 2.2.9 on 2020-01-17 20:09

import common.enums
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
import enumfields.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('registered', models.BooleanField(null=True)),
                ('voter_status', enumfields.fields.EnumField(enum=common.enums.VoterStatus, max_length=10, null=True)),
                ('total_matches', models.IntegerField()),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('gender', enumfields.fields.EnumField(enum=common.enums.CatalistGender, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('catalist_stateid', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Zip codes are 5 digits')])),
                ('county', models.TextField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
