# Generated by Django 2.2.9 on 2020-01-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('election', '0001_initial'),
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='people.Person'),
        ),
        migrations.AddField(
            model_name='lookup',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='election.State'),
            preserve_default=False,
        ),
    ]
