# Generated by Django 2.2.9 on 2020-01-27 19:16

import common.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='gender',
            field=enumfields.fields.EnumField(enum=common.enums.TargetSmartGender, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='registered',
            field=enumfields.fields.EnumField(enum=common.enums.VoterStatus, max_length=10, null=True),
        ),
    ]
