# Generated by Django 2.2.9 on 2020-01-27 19:23

import common.enums
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_auto_20200127_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='voter_status',
            field=enumfields.fields.EnumField(enum=common.enums.VoterStatus, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='registered',
            field=models.BooleanField(null=True),
        ),
    ]
