# Generated by Django 2.2.12 on 2020-04-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('verifier', '0008_verifier_sms_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='action',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Action'),
        ),
    ]
