# Generated by Django 2.2.12 on 2020-04-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0009_lookup_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookup',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='lookup',
            name='street_number',
        ),
    ]
