# Generated by Django 2.2.12 on 2020-04-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0012_enumchartotextfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
