# Generated by Django 2.2.12 on 2020-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0013_lookup_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='sms_opt_in_partner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
