# Generated by Django 2.2.13 on 2020-07-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0017_lookup_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='embed_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
