# Generated by Django 2.2.14 on 2020-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0018_tracking_embed_url_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='email_referrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='mobile_referrer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
