# Generated by Django 2.2.15 on 2020-08-22 16:36

import common.enums
import common.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0020_smalluuid_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='alloy_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='alloy_status',
            field=common.fields.TurnoutEnumField(enum=common.enums.VoterStatus, null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='targetsmart_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='lookup',
            name='targetsmart_status',
            field=common.fields.TurnoutEnumField(enum=common.enums.VoterStatus, null=True),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
