# Generated by Django 2.2.10 on 2020-02-18 20:21

import common.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_load_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateinformationfieldtype',
            name='field_format',
            field=enumfields.fields.EnumField(enum=common.enums.StateFieldFormats, max_length=10, null=True, default=common.enums.StateFieldFormats.MARKDOWN),
        ),
    ]
