# Generated by Django 2.2.10 on 2020-02-25 17:46

import common.enums
from django.db import migrations, models
import django_smalluuid.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_stateinformationfieldtype_field_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateNotificationWebhook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(null=True)),
                ('type', enumfields.fields.EnumField(enum=common.enums.NotificationWebhookTypes, max_length=10, null=True)),
                ('trigger_url', models.URLField(null=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
