# Generated by Django 2.2.12 on 2020-06-02 18:57

from django.db import migrations

import common.enums
import common.fields


def georgia_email_esign(apps, schema_editor):
    State = apps.get_model("election", "State")
    georgia = State.objects.get(code="GA")

    georgia.vbm_submission_type = common.enums.SubmissionType.LEO_EMAIL
    georgia.save()


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0005_enumchartotextfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="vbm_submission_type",
            field=common.fields.TurnoutEnumField(
                default="self_print", enum=common.enums.SubmissionType
            ),
        ),
        migrations.RunPython(georgia_email_esign, lambda x, y: None),
    ]
