# Generated by Django 2.2.13 on 2020-06-29 22:52

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_stateinformationfieldtype_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='vbm_submission_type',
            field=common.fields.TurnoutEnumField(default='self_print', enum=common.enums.SubmissionType, null=True),
        ),
    ]
