# Generated by Django 2.2.14 on 2020-07-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20200629_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='vbm_submission_type',
        ),
    ]
