# Generated by Django 2.2.15 on 2020-08-10 13:47

from django.db import migrations, models

from election.choices import TERRITORIES


def mark_territories(apps, schema_editor):
    State = apps.get_model("election", "State")
    for state in TERRITORIES:
        obj = State.objects.get(code=state[0])
        obj.territory = True
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0011_add_territories"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="territory",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RunPython(mark_territories, lambda x, y: None),
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(
                choices=[
                    ("AL", "AL"),
                    ("AK", "AK"),
                    ("AZ", "AZ"),
                    ("AR", "AR"),
                    ("CA", "CA"),
                    ("CO", "CO"),
                    ("CT", "CT"),
                    ("DE", "DE"),
                    ("FL", "FL"),
                    ("GA", "GA"),
                    ("HI", "HI"),
                    ("ID", "ID"),
                    ("IL", "IL"),
                    ("IN", "IN"),
                    ("IA", "IA"),
                    ("KS", "KS"),
                    ("KY", "KY"),
                    ("LA", "LA"),
                    ("ME", "ME"),
                    ("MD", "MD"),
                    ("MA", "MA"),
                    ("MI", "MI"),
                    ("MN", "MN"),
                    ("MS", "MS"),
                    ("MO", "MO"),
                    ("MT", "MT"),
                    ("NE", "NE"),
                    ("NV", "NV"),
                    ("NH", "NH"),
                    ("NJ", "NJ"),
                    ("NM", "NM"),
                    ("NY", "NY"),
                    ("NC", "NC"),
                    ("ND", "ND"),
                    ("OH", "OH"),
                    ("OK", "OK"),
                    ("OR", "OR"),
                    ("PA", "PA"),
                    ("RI", "RI"),
                    ("SC", "SC"),
                    ("SD", "SD"),
                    ("TN", "TN"),
                    ("TX", "TX"),
                    ("UT", "UT"),
                    ("VT", "VT"),
                    ("VA", "VA"),
                    ("WA", "WA"),
                    ("WV", "WV"),
                    ("WI", "WI"),
                    ("WY", "WY"),
                    ("DC", "DC"),
                    ("AS", "AS"),
                    ("GU", "GU"),
                    ("MP", "MP"),
                    ("PR", "PR"),
                    ("VI", "VI"),
                ],
                editable=False,
                max_length=2,
                primary_key=True,
                serialize=False,
                verbose_name="Code",
            ),
        ),
    ]
