# Generated by Django 2.2.15 on 2020-08-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_add_territory_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='allow_print_and_forward',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
