# Generated by Django 2.2.16 on 2020-09-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_state_allow_print_and_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='allow_absentee_print_and_forward',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
