# Generated by Django 2.2.15 on 2020-08-17 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smsbot', '0002_smalluuid_to_uuid'),
        ('election', '0012_add_territory_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSEarlyVoteAndBallot',
            fields=[
                ('smartvan_id', models.CharField(max_length=100, null=True)),
                ('voterbase_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('voterid', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(db_index=True, max_length=2, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('county_id', models.CharField(max_length=100, null=True)),
                ('request_received_date', models.DateField(null=True)),
                ('ballot_mailed_date', models.DateField(null=True)),
                ('ballot_received_date', models.DateField(null=True)),
                ('early_voted_date', models.DateField(null=True)),
                ('ballot_party', models.CharField(max_length=100, null=True)),
                ('ballot_canceled', models.DateField(null=True)),
                ('application_mailed', models.DateField(null=True)),
                ('tsmart_requested', models.CharField(max_length=100, null=True)),
                ('tsmart_voted', models.CharField(max_length=100, null=True)),
                ('election_date', models.DateField(null=True)),
                ('ev_data_update_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'ts_early_vote_and_ballot',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_voter_id', models.TextField(null=True)),
                ('last_state_refresh', models.DateField(null=True)),
                ('alloy_person_id', models.IntegerField(null=True)),
                ('last_alloy_refresh', models.DateTimeField(null=True)),
                ('ts_voterbase_id', models.TextField(null=True)),
                ('last_ts_refresh', models.DateTimeField(null=True)),
                ('registered', models.BooleanField(null=True)),
                ('registration_date', models.DateField(null=True)),
                ('last_registration_refresh', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('first_name', models.TextField(null=True)),
                ('middle_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('suffix', models.TextField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address_full', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('zipcode', models.TextField(null=True)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsbot.Number')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='election.State')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
