# Generated by Django 2.2.15 on 2020-08-26 21:48

import uuid
from django.db import migrations, models


## This is based on https://stackoverflow.com/questions/38311503/django-1-9-drop-foreign-key-in-migration

class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    database_operations = [
        migrations.RunSQL("UPDATE voter_voter SET phone_id=NULL"),
        # remove DB constraint so that we can make this not a PK on smsbot_number
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.ForeignKey(
                null=True,
                db_constraint=False,
                on_delete=models.deletion.SET_NULL,
                to='smsbot.Number'
            ),
        ),
    ]

    state_operations = [
        # now make it a simple UUID field (not a foreign key)
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='phone',
            new_name='phone_id'
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
