# Generated by Django 2.2.15 on 2020-08-26 21:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_clear_voter_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
