# Generated by Django 2.2.16 on 2020-09-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_json_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='alloy_person_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state_voter_id',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='ts_voterbase_id',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
