# Generated by Django 2.2.16 on 2020-11-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_index_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='registered',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['created_at'], name='voter_voter_created_9a545e_idx'),
        ),
    ]
