# Generated by Django 2.2.9 on 2020-01-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_load_states'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default='AL', on_delete=django.db.models.deletion.PROTECT, related_name='person_addresses', to='election.State'),
            preserve_default=False,
        ),
    ]
