# Generated by Django 2.2.12 on 2020-04-17 02:36

import common.fields
from django.db import migrations
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=common.fields.TurnoutEnumField(db_index=True, enum=people.models.PhoneType),
        ),
    ]
