# Generated by Django 2.2.12 on 2020-05-28 18:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0002_address_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326)),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='official.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
