# Generated by Django 2.2.13 on 2020-06-11 21:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0004_delete_regionshape'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionGeomMA',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('town', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'official_region_geom_ma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionGeomWI',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('mcd_name', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'official_region_geom_wi',
                'managed': False,
            },
        ),
    ]
