# Generated by Django 2.2.14 on 2020-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0005_regiongeomma_regiongeomwi'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='hidden',
            field=models.BooleanField(null=True),
        ),
    ]
