# Generated by Django 2.2.11 on 2020-03-31 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenant', '0004_inviteassociation'),
        ('register', '0004_registration_result_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='multi_tenant.Client'),
        ),
    ]
