# Generated by Django 2.2.12 on 2020-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_registration_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sms_opt_in',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
