# Generated by Django 2.2.12 on 2020-04-17 02:36

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_sms_opt_in_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=common.fields.TurnoutEnumField(enum=common.enums.RegistrationGender, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='party',
            field=common.fields.TurnoutEnumField(enum=common.enums.PoliticalParties, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='previous_title',
            field=common.fields.TurnoutEnumField(blank=True, enum=common.enums.PersonTitle, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='race_ethnicity',
            field=common.fields.TurnoutEnumField(enum=common.enums.RaceEthnicity, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=common.fields.TurnoutEnumField(default='Pending', enum=common.enums.TurnoutActionStatus, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='title',
            field=common.fields.TurnoutEnumField(enum=common.enums.PersonTitle, null=True),
        ),
    ]
