# Generated by Django 2.2.12 on 2020-05-20 20:51

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_utm_term_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='referring_tool',
            field=common.fields.TurnoutEnumField(blank=True, enum=common.enums.ToolName, null=True),
        ),
    ]
