# Generated by Django 2.2.13 on 2020-06-15 14:54

from django.db import migrations

import tsvector_field


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0013_rename_partner_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="search",
            field=tsvector_field.SearchVectorField(
                columns=[
                    tsvector_field.WeightedColumn("email", "A"),
                    tsvector_field.WeightedColumn("last_name", "A"),
                    tsvector_field.WeightedColumn("first_name", "A"),
                ],
                language="english",
            ),
        ),
        tsvector_field.IndexSearchVector("registration", "search"),
    ]
