# Generated by Django 2.2.13 on 2020-06-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_registration_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='custom_ovr_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
