# Generated by Django 2.2.13 on 2020-07-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_registration_custom_ovr_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='embed_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
