# Generated by Django 2.2.15 on 2020-08-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0006_region_hidden'),
        ('register', '0019_smalluuid_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='matched_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='official.Region'),
        ),
        migrations.AddField(
            model_name='registration',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='official.Region'),
        ),
    ]
