# Generated by Django 2.2.14 on 2020-07-19 22:48

import common.enums
import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
import phonenumber_field.modelfields
import tsvector_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multi_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('search', tsvector_field.SearchVectorField(columns=[tsvector_field.WeightedColumn('organization_name', 'A'), tsvector_field.WeightedColumn('first_name', 'A'), tsvector_field.WeightedColumn('last_name', 'A'), tsvector_field.WeightedColumn('email', 'A')], language='english')),
                ('organization_name', models.TextField(null=True)),
                ('website', models.URLField(null=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('nonprofit', models.BooleanField(null=True)),
                ('ein', models.TextField(blank=True, null=True)),
                ('status', common.fields.TurnoutEnumField(default='pending', enum=common.enums.SubscriptionInterestStatus, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('months', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField(null=True)),
                ('public', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['public', 'months'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('expires', models.DateField(blank=True, db_index=True, null=True)),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Interest')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Product')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multi_tenant.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interest',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Product'),
        ),
    ]
