# Generated by Django 2.2.14 on 2020-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='reject_reason',
            field=models.TextField(null=True),
        ),
    ]
