# Generated by Django 2.2.15 on 2020-08-06 19:54

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_smalluuid_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='sms_mode',
            field=common.fields.TurnoutEnumField(default='box_unchecked', enum=common.enums.SubscriberSMSOption, null=True),
        ),
    ]
