# Generated by Django 2.2.16 on 2020-12-08 18:38

import common.enums
import common.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db.models import Case, Value, When, F
from django.template.defaultfilters import pluralize


def migrate_plans(apps, schema_editor):
    # We could *maybe* do this with bulk updates, but it would be much more
    # complicated and involve a bunch of subquries to copy fields from Interest
    # to Subscription: https://stackoverflow.com/a/50561753
    #
    # We're working with ~100 records here, so this is fine.

    Interest = apps.get_model("subscription", "Interest")
    for interest in Interest.objects.all():
        if interest.nonprofit:
            interest.plan = common.enums.SubscriberPlan.NONPROFIT
        else:
            interest.plan = common.enums.SubscriberPlan.PREMIUM

        interest.save()

    Subscription = apps.get_model("subscription", "Subscription")
    for subscription in Subscription.objects.all():
        subscription.plan = subscription.interest.plan
        subscription.primary_contact_first_name = subscription.interest.first_name
        subscription.primary_contact_last_name = subscription.interest.last_name
        subscription.primary_contact_phone = subscription.interest.phone
        subscription.primary_contact_email = subscription.interest.email

        # For some reason, inside migrations the __str__ property of Product
        # doesn't work and we get a default representation
        subscription.internal_notes = f"Legacy plan selection: {subscription.product.months} month{pluralize(subscription.product.months)} at ${subscription.product.cost} per month"

        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_interest_sms_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="plan",
            field=common.fields.TurnoutEnumField(
                default="free", enum=common.enums.SubscriberPlan, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="internal_notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=common.fields.TurnoutEnumField(
                default="free", enum=common.enums.SubscriberPlan, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="primary_contact_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="primary_contact_first_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="primary_contact_last_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="primary_contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscriber",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="multi_tenant.Client"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="internal_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_plans, lambda x, y: None),
    ]
