# Generated by Django 2.2.16 on 2020-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0006_new_subscriber_plans"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW subscription_reportview AS
            SELECT
                client.name AS subscriber_name,
                slug.slug AS subscriber_slug,
                subscription.plan AS plan,
                subscription.primary_contact_first_name AS primary_contact_first_name,
                subscription.primary_contact_last_name AS primary_contact_last_name,
                subscription.primary_contact_email AS primary_contact_email,
                subscription.primary_contact_phone AS primary_contact_phone,
                subscription.internal_notes AS internal_notes
            FROM subscription_subscription subscription
            JOIN multi_tenant_client client ON subscription.subscriber_id = client.uuid
            JOIN multi_tenant_partnerslug slug ON client.default_slug_id = slug.uuid;

            CREATE OR REPLACE VIEW subscription_userreportview AS
            SELECT
                client.name AS subscriber_name,
                slug.slug AS subscriber_slug,
                subscription.plan AS plan,
                accounts_user.first_name,
                accounts_user.last_name,
                accounts_user.email,
                accounts_user.last_login AS last_login_utc,
                accounts_user.created_at AS account_created_at_utc,
                accounts_user.timezone AS user_local_timezone
            FROM subscription_subscription subscription
            JOIN multi_tenant_client client ON subscription.subscriber_id = client.uuid
            JOIN multi_tenant_partnerslug slug ON client.default_slug_id = slug.uuid
            JOIN multi_tenant_association assoc ON assoc.client_id = client.uuid
            JOIN accounts_user ON assoc.user_id = accounts_user.uuid;
            """,
            reverse_sql="""
            DROP VIEW subscription_reportview;
            DROP VIEW subscription_userreportview;
            """,
        )
    ]
