# Generated by Django 2.2.17 on 2020-12-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_subscription_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ein',
            field=models.TextField(blank=True, null=True),
        ),
    ]
