# Generated by Django 2.2.16 on 2020-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0008_subscription_ein"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW subscription_reportview;
            CREATE VIEW subscription_reportview AS
            WITH first_user_create_times AS (
                SELECT
                    assoc.client_id,
                    MIN(u.created_at) AS first_user_created
                FROM multi_tenant_association assoc
                JOIN accounts_user u ON assoc.user_id = u.uuid
                GROUP BY assoc.client_id
            )

            SELECT
                client.name AS subscriber_name,
                slug.slug AS subscriber_slug,
                subscription.plan AS plan,
                subscription.primary_contact_first_name AS primary_contact_first_name,
                subscription.primary_contact_last_name AS primary_contact_last_name,
                subscription.primary_contact_email AS primary_contact_email,
                subscription.primary_contact_phone AS primary_contact_phone,
                subscription.ein AS ein,
                client.created_at AS created_at,
                first_user_create_times.first_user_created,
                CASE WHEN interest.nonprofit OR subscription.plan = 'nonprofit' THEN 'YES' ELSE 'NO' END AS nonprofit,
                client.url,
                client.privacy_policy,
                CASE
                    WHEN NOT client.sms_enabled THEN 'None'
                    WHEN NOT client.sms_checkbox THEN 'No Checkbox; Auto-opt-in'
                    WHEN client.sms_checkbox_default THEN 'Default Checked'
                    ELSE 'Default Unchecked'
                END AS sms_checkbox_setting,
                client.sms_disclaimer AS custom_sms_disclaimer,
                CASE WHEN client.has_api_access THEN 'YES' ELSE 'NO' END AS has_action_api_access,
                CASE WHEN subscription.plan != 'free' AND client.sync_tmc THEN 'YES' ELSE 'NO' END AS tmc_sync_enabled,
                CASE WHEN subscription.plan != 'free' AND  client.sync_bluelink THEN 'YES' ELSE 'NO' END AS bluelink_sync_enabled,
                CASE WHEN subscription.plan != 'free' AND  sip.value IS NOT NULL AND sip.value != '' THEN 'YES' ELSE 'NO' END AS actionnetwork_sync_enabled,
                subscription.internal_notes AS internal_notes
            FROM subscription_subscription subscription
            JOIN multi_tenant_client client ON subscription.subscriber_id = client.uuid
            JOIN multi_tenant_partnerslug slug ON client.default_slug_id = slug.uuid
            LEFT JOIN subscription_interest interest ON subscription.interest_id = interest.uuid
            LEFT JOIN first_user_create_times ON first_user_create_times.client_id = client.uuid
            LEFT JOIN multi_tenant_subscriberintegrationproperty sip ON sip.subscriber_id = client.uuid AND sip.external_tool = 'actionnetwork' AND sip.name = 'api_key';
            """,
            reverse_sql="",
        )
    ]
